### ISSUE TITLE
Make onDesiredPropertiesUpdate async

### ISSUE THREAD

**Issue by sandervandevelde** [iot-edge-foundation/iot-edge-heartbeat#1]
onDesiredPropertiesUpdate is not awaitable:

    private static Task onDesiredPropertiesUpdate(TwinCollection desiredProperties, object userContext)
    ....
    client.UpdateReportedPropertiesAsync(reportedProperties).ConfigureAwait(false);

**Comment by JeeWeetje** [comment]
Closed due to inactivity.
